services:
  # ✅ Backend (Node.js + Express + PostgreSQL)
  - type: web
    name: mob13r-api
    env: node
    region: singapore
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        value: dpg-d3k0cj3ipnbc73a29bcg-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: mob13r_db_bt1m
      - key: DB_USER
        value: mob13r_db_bt1m_user
      - key: DB_PASS
        value: mjRkuM8X9XVaH2kJA0JnVnKjfSH6NE9i
      - key: JWT_SECRET
        value: mob13r_secret_key
      - key: ADMIN_EMAIL
        value: ruhil.13r@gmail.com
      - key: ADMIN_PASSWORD
        value: Anil@1234
      - key: FRONTEND_URL
        value: https://dashboard.mob13r.com

  # ✅ Frontend (React App)
  - type: web
    name: mob13r-dashboard
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://mob13r-platform.onrender.com/api
      - key: REACT_APP_APP_NAME
        value: Mob13r.api
      - key: REACT_APP_THEME
        value: dark

databases:
  # ✅ PostgreSQL Database (already created on Render)
  - name: mob13r-db
