import apiClient from "../api/apiClient";
import { useEffect, useState } from "react";

export default function useDistributionLogic() {
  // -------------------------------
  // STATES
  // -------------------------------
  const [publishers, setPublishers] = useState([]);
  const [trackingLinks, setTrackingLinks] = useState([]);
  const [rules, setRules] = useState([]);
  const [offers, setOffers] = useState([]);
  const [remainingPercent, setRemainingPercent] = useState(100);

  const [selectedPublisher, setSelectedPublisher] = useState("");
  const [selectedTrackingLink, setSelectedTrackingLink] = useState("");

  const [form, setForm] = useState({
    geo: "",
    carrier: "",
    offerId: "",
    percentage: "",
    isFallback: false
  });

  // -------------------------------
  // 1. LOAD ALL PUBLISHERS
  // -------------------------------
  const loadPublishers = async () => {
    const res = await apiClient.get("/publishers");
    setPublishers(res.data);
  };

  // -------------------------------
  // 2. LOAD TRACKING LINKS (AUTOGENERATED PUB01/PUB02/PUB03 URLs)
  // -------------------------------
  const loadTrackingLinks = async (publisherId) => {
    const res = await apiClient.get(`/tracking-links?publisher_id=${publisherId}`);
    setTrackingLinks(res.data);
  };

  // -------------------------------
  // 3. LOAD DISTRIBUTION RULES
  // -------------------------------
  const loadRules = async (trackingLinkId) => {
    const res = await apiClient.get(`/distribution/rules?tracking_link_id=${trackingLinkId}`);
    setRules(res.data);
  };

  // -------------------------------
  // 4. LOAD REMAINING %
  // -------------------------------
  const loadRemainingPercent = async (trackingLinkId) => {
    const res = await apiClient.get(`/distribution/rules/remaining?tracking_link_id=${trackingLinkId}`);
    setRemainingPercent(res.data.remainingPercentage);
  };

  // -------------------------------
  // 5. LOAD ADVERTISER OFFERS FOR SELECTED GEO + CARRIER
  // -------------------------------
  const loadOffers = async (geo, carrier) => {
    if (!geo || !carrier) return;

    const res = await apiClient.get(`/offers?geo=${geo}&carrier=${carrier}`);
    setOffers(res.data);
  };

  // -------------------------------
  // HANDLE PUBLISHER SELECT
  // -------------------------------
  const handlePublisherSelect = async (publisherId) => {
    setSelectedPublisher(publisherId);
    setSelectedTrackingLink("");
    setRules([]);
    setOffers([]);

    if (publisherId) loadTrackingLinks(publisherId);
  };

  // -------------------------------
  // HANDLE TRACKING LINK SELECT
  // -------------------------------
  const handleTrackingLinkSelect = async (trackingLinkId) => {
    setSelectedTrackingLink(trackingLinkId);

    const link = trackingLinks.find(t => t.id == trackingLinkId);
    if (link) {
      // Autofill GEO + Carrier
      setForm(prev => ({
        ...prev,
        geo: link.geo,
        carrier: link.carrier
      }));

      // Load offers for this geo + carrier
      await loadOffers(link.geo, link.carrier);

      // Load rules
      await loadRules(trackingLinkId);

      // Load remaining percent
      await loadRemainingPercent(trackingLinkId);
    }
  };

  // -------------------------------
  // HANDLE INPUT CHANGE
  // -------------------------------
  const handleInputChange = (field, value) => {
    setForm({ ...form, [field]: value });

    if (field === "geo" || field === "carrier") {
      loadOffers(
        field === "geo" ? value : form.geo,
        field === "carrier" ? value : form.carrier
      );
    }
  };

  // -------------------------------
  // ADD NEW DISTRIBUTION RULE
  // -------------------------------
  const addRule = async () => {
    if (!selectedTrackingLink) return alert("Select tracking link first!");
    if (!form.offerId) return alert("Select an offer!");

    // % validation
    if (Number(form.percentage) > Number(remainingPercent)) {
      return alert(`You have only ${remainingPercent}% remaining.`);
    }

    const payload = {
      tracking_link_id: selectedTrackingLink,
      offer_id: form.offerId,
      geo: form.geo,
      carrier: form.carrier,
      percentage: Number(form.percentage),
      is_fallback: form.isFallback
    };

    await apiClient.post("/distribution/rules", payload);

    await loadRules(selectedTrackingLink);
    await loadRemainingPercent(selectedTrackingLink);

    resetForm();
  };

  // -------------------------------
  // UPDATE RULE
  // -------------------------------
  const updateRule = async (id, updatedData) => {
    await apiClient.put(`/distribution/rules/${id}`, updatedData);

    await loadRules(selectedTrackingLink);
    await loadRemainingPercent(selectedTrackingLink);
  };

  // -------------------------------
  // DELETE RULE
  // -------------------------------
  const deleteRule = async (id) => {
    await apiClient.delete(`/distribution/rules/${id}`);

    await loadRules(selectedTrackingLink);
    await loadRemainingPercent(selectedTrackingLink);
  };

  // -------------------------------
  // RESET FORM
  // -------------------------------
  const resetForm = () => {
    setForm({
      geo: "",
      carrier: "",
      offerId: "",
      percentage: "",
      isFallback: false
    });
  };

  // -------------------------------
  // INITIAL LOAD
  // -------------------------------
  useEffect(() => {
    loadPublishers();
  }, []);

  return {
    publishers,
    trackingLinks,
    rules,
    offers,

    selectedPublisher,
    selectedTrackingLink,
    remainingPercent,
    form,

    handlePublisherSelect,
    handleTrackingLinkSelect,
    handleInputChange,

    addRule,
    updateRule,
    deleteRule
  };
}
