import express from "express";
import nodemailer from "nodemailer";
import pool from "../db.js";
import orgAuth from "../middleware/orgAuth.js";
import PDFDocument from "pdfkit";

const router = express.Router();

/* Helper: Generate PDF directly (no HTTP call needed) */
async function generateDocsPDF(publisher_id, offer_id, orgId) {
  return new Promise(async (resolve, reject) => {
    try {
      // Fetch publisher + offer data
      const pubRes = await pool.query(
        "SELECT id, api_key, name FROM publishers WHERE id=$1 AND org_id=$2",
        [publisher_id, orgId]
      );
      if (!pubRes.rows.length) return reject(new Error("Publisher not found"));
      const publisher = pubRes.rows[0];

      const offerRes = await pool.query(
        `SELECT o.id, o.geo, o.carrier, o.service_name, o.pin_send_url, o.pin_verify_url, o.otp_length,
                COALESCE(po.pub_offer_name, o.service_name) AS display_name
         FROM offers o
         LEFT JOIN publisher_offers po ON po.offer_id = o.id AND po.publisher_id = $2
         WHERE o.id = $1 LIMIT 1`,
        [offer_id, publisher_id]
      );
      if (!offerRes.rows.length) return reject(new Error("Offer not found"));
      const offer = offerRes.rows[0];

      const BACKEND = "https://backend.mob13r.com";
      const pinSendUrl = `${BACKEND}/api/publisher/pin/send?offer_id=${offer_id}&msisdn={msisdn}&geo=${offer.geo}&carrier=${offer.carrier}&x-api-key=${publisher.api_key}`;
      const pinVerifyUrl = `${BACKEND}/api/publisher/pin/verify?session_token={session_token}&otp={otp}&x-api-key=${publisher.api_key}`;

      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];
      doc.on("data", chunk => chunks.push(chunk));
      doc.on("end", () => resolve({ buffer: Buffer.concat(chunks), offer, publisher }));

      // Header
      doc.fontSize(20).fillColor("#e94560").text("mob13r", { continued: true });
      doc.fillColor("#1a1a2e").text(" — API Documentation", { align: "left" });
      doc.moveDown(0.5);
      doc.fontSize(14).fillColor("#333").text(`Service: ${offer.display_name}`);
      doc.fontSize(12).fillColor("#666").text(`Geo: ${offer.geo}  |  Carrier: ${offer.carrier}  |  OTP Length: ${offer.otp_length || 4}`);
      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke("#e2e8f0");
      doc.moveDown();

      // PIN SEND
      doc.fontSize(14).fillColor("#1a1a2e").text("1. PIN SEND (Generate OTP)");
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#555").text("Initialize the subscription flow with user's mobile number.");
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor("#0a0f1e").rect(50, doc.y, 500, 50).fill("#0a0f1e");
      doc.fillColor("#94fcb5").text(pinSendUrl, 60, doc.y - 42, { width: 480, lineBreak: true });
      doc.moveDown(2);

      // PIN VERIFY
      doc.fontSize(14).fillColor("#1a1a2e").text("2. PIN VERIFY (Confirm OTP)");
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#555").text("Confirm the OTP entered by user to complete subscription.");
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor("#0a0f1e").rect(50, doc.y, 500, 50).fill("#0a0f1e");
      doc.fillColor("#94fcb5").text(pinVerifyUrl, 60, doc.y - 42, { width: 480, lineBreak: true });
      doc.moveDown(2);

      // Parameters table
      doc.fontSize(14).fillColor("#1a1a2e").text("Parameters");
      doc.moveDown(0.5);
      const params = [
        ["offer_id", `${offer_id}`, "Offer identifier"],
        ["msisdn", "{msisdn}", "User mobile number with country code"],
        ["geo", offer.geo, "Country code"],
        ["carrier", offer.carrier, "Carrier name"],
        ["x-api-key", publisher.api_key, "Your publisher API key"],
        ["session_token", "{session_token}", "Returned from PIN SEND response"],
        ["otp", "{otp}", "OTP entered by user"],
      ];
      let y = doc.y;
      doc.fontSize(10).fillColor("#fff").rect(50, y, 500, 20).fill("#1a1a2e");
      doc.text("Parameter", 55, y + 5).text("Value", 200, y + 5).text("Description", 320, y + 5);
      y += 20;
      params.forEach((row, i) => {
        doc.fillColor(i % 2 === 0 ? "#f8fafc" : "#fff").rect(50, y, 500, 20).fill();
        doc.fillColor("#333").text(row[0], 55, y + 5).text(row[1], 200, y + 5, { width: 115 }).text(row[2], 320, y + 5, { width: 225 });
        y += 20;
      });
      doc.moveDown(2);

      doc.fontSize(10).fillColor("#999").text(`Generated by mob13r Platform | ${new Date().toLocaleDateString()}`, { align: "center" });
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/* POST /api/email/send-docs */
router.post("/email/send-docs", orgAuth, async (req, res) => {
  try {
    const { publisher_id, offer_id, to_email, custom_message } = req.body;

    if (!publisher_id || !offer_id || !to_email) {
      return res.status(400).json({ status: "FAILED", error: "publisher_id, offer_id, to_email required" });
    }

    // Generate PDF directly
    let pdfBuffer, offer, publisher;
    try {
      ({ buffer: pdfBuffer, offer, publisher } = await generateDocsPDF(publisher_id, offer_id, req.orgId));
    } catch (pdfErr) {
      console.error("PDF generation error:", pdfErr);
      return res.status(500).json({ status: "FAILED", error: "PDF generation failed: " + pdfErr.message });
    }

    // Setup transporter
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || "smtp-relay.brevo.com",
      port: Number(process.env.SMTP_PORT) || 587,
      secure: false,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    const senderName = process.env.SMTP_FROM_NAME || "mob13r Platform";
    const fileName = `API_Docs_${offer.display_name}_${offer.geo}_${offer.carrier}.pdf`.replace(/\s+/g, "_");

    await transporter.sendMail({
      from: `"${senderName}" <${process.env.SMTP_FROM_EMAIL || process.env.SMTP_USER}>`,
      to: to_email,
      subject: `API Integration Docs — ${offer.display_name} (${offer.geo} | ${offer.carrier})`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: #1a1a2e; padding: 24px; border-radius: 12px 12px 0 0;">
            <h2 style="color: #e94560; margin: 0;">mob13r</h2>
            <p style="color: #94a3b8; margin: 4px 0 0;">API Integration Documentation</p>
          </div>
          <div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
            <p style="color: #1e293b;">Hi <strong>${publisher.name}</strong>,</p>
            <p style="color: #475569;">Please find attached the API integration documentation for:</p>
            <div style="background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0;">
              <p style="margin: 4px 0; color: #1e293b;"><strong>Offer:</strong> ${offer.display_name}</p>
              <p style="margin: 4px 0; color: #1e293b;"><strong>Geo:</strong> ${offer.geo}</p>
              <p style="margin: 4px 0; color: #1e293b;"><strong>Carrier:</strong> ${offer.carrier}</p>
            </div>
            ${custom_message ? `<p style="color: #475569; border-left: 3px solid #e94560; padding-left: 12px;">${custom_message}</p>` : ""}
            <p style="color: #475569;">The PDF document contains all API endpoints, parameters, and integration guidelines.</p>
            <p style="color: #94a3b8; font-size: 13px; margin-top: 24px;">— ${senderName}</p>
          </div>
        </div>
      `,
      attachments: [{ filename: fileName, content: pdfBuffer, contentType: "application/pdf" }],
    });

    // Log email in DB
    await pool.query(
      `INSERT INTO email_logs (publisher_id, offer_id, to_email, subject, status, org_id, sent_at)
       VALUES ($1, $2, $3, $4, 'sent', $5, NOW())
       ON CONFLICT DO NOTHING`,
      [publisher_id, offer_id, to_email, `API Docs — ${offer.display_name} (${offer.geo}|${offer.carrier})`, req.orgId]
    );

    res.json({ status: "SUCCESS", message: `Email sent to ${to_email} with PDF attached` });

  } catch (err) {
    console.error("Email send error:", err);

    // Log failed email
    try {
      const { publisher_id, offer_id, to_email } = req.body;
      await pool.query(
        `INSERT INTO email_logs (publisher_id, offer_id, to_email, subject, status, error, org_id, sent_at)
         VALUES ($1, $2, $3, 'API Docs', 'failed', $4, $5, NOW())`,
        [publisher_id, offer_id, to_email, err.message, req.orgId]
      );
    } catch (_) {}

    res.status(500).json({ status: "FAILED", error: err.message });
  }
});

/* GET /api/email/logs — Email sent history */
router.get("/email/logs", orgAuth, async (req, res) => {
  try {
    const { limit = 100, offset = 0 } = req.query;
    const result = await pool.query(
      `SELECT el.*, p.name AS publisher_name, o.service_name AS offer_name,
              COALESCE(po.pub_offer_name, o.service_name) AS display_name
       FROM email_logs el
       LEFT JOIN publishers p ON p.id = el.publisher_id
       LEFT JOIN offers o ON o.id = el.offer_id
       LEFT JOIN publisher_offers po ON po.publisher_id = el.publisher_id AND po.offer_id = el.offer_id
       WHERE el.org_id = $1
       ORDER BY el.sent_at DESC
       LIMIT $2 OFFSET $3`,
      [req.orgId, Number(limit), Number(offset)]
    );
    res.json({ status: "SUCCESS", data: result.rows, total: result.rows.length });
  } catch (err) {
    res.status(500).json({ status: "FAILED", error: err.message });
  }
});

export default router;
