name: Make migration script executable

on:
  push:
    branches: [ "main" ]

jobs:
  fix-permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set execute permission for migrate script
        run: chmod +x .platform/hooks/postdeploy/01_migrate.sh

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Make EB migrate script executable"
